### ISSUE TITLE
How do we export IV

### ISSUE THREAD

**Issue by subu1979** [Havner/yaca#4]
Tried the below code

char *export_aes_iv()
{
	yaca_key_h iv = YACA_KEY_NULL;	
	size_t iv_bit_len;	

	char *b64 = NULL;
	size_t b64_len;

	yaca_initialize();
	yaca_encrypt_get_iv_bit_length(YACA_ENCRYPT_AES, YACA_BCM_CTR, YACA_KEY_LENGTH_256BIT,&iv_bit_len);

	if (iv_bit_len > 0) {
		yaca_key_generate(YACA_KEY_TYPE_IV, iv_bit_len, &iv);	
	}	
	yaca_key_export(iv, YACA_KEY_FORMAT_DEFAULT, YACA_KEY_FILE_FORMAT_BASE64,NULL,&b64, &b64_len);
	yaca_cleanup();	
	return b64;
}

yaca_key_h import_aes_iv(char *b64_iv)
{
	yaca_key_h iv = YACA_KEY_NULL;

	yaca_initialize();
	yaca_key_import(YACA_KEY_TYPE_IV, NULL, b64_iv, strlen(b64_iv), &iv);
	yaca_cleanup();
	return iv;
}

**Comment by Havner** [comment]
Ok, but what is the issue you have?

Looking at the code above the first issue I see is that exported b64 is not a string. It does not contain a trailing zero so you cannot use strlen on it. You need to remember and pass the b64_len to import it again.

**Comment by subu1979** [comment]
Hi Havner,

Thanks. I used a struct to store both iv & size .

Made a working wrapper.

Thanks for your inputs.
