### ISSUE TITLE
Fixed IV 

### ISSUE THREAD

**Issue by subu1979** [Havner/yaca#6]
//Fixed IV - 256bit
char const_iv[] ="t7LlMklp5s5HlxSm37EHK203T8FnV513";	
yaca_key_h iv = (yaca_key_h)(const_iv);

Tried the above code in encryption & decryption, it failed.

Is there any way we can have a fixed IV

**Comment by Havner** [comment]
You need to import this table as a key.

With all due respect, but you are reporting "issues" in yaca which are not really any issues. And this place is not really a help desk.
